# Generated by Django 2.2 on 2019-04-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.PositiveIntegerField()),
                ('booking_type', models.CharField(choices=[('full day', 'FUll Day'), ('first Half', 'First Half'), ('second Half', 'Second Half')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('booking_purpose', models.ManyToManyField(to='venue.BookingPurpose')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.State')),
            ],
        ),
    ]
