# Generated by Django 2.2 on 2019-04-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20190412_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='booking_type',
            field=models.CharField(choices=[('full day', 'Full Day'), ('first Half', 'First Half'), ('second Half', 'Second Half')], max_length=15),
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Venue')),
            ],
        ),
    ]
