# Generated by Django 2.2 on 2019-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_auto_20190414_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuebooking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
