# Generated by Django 2.2 on 2019-04-14 15:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20190414_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='booking_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full_day', 'Full Day'), ('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=31),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='booking_id',
            field=models.CharField(blank=True, help_text='Unique Booking Id will Be auto Generate by System', max_length=15, null=True),
        ),
    ]
