# Generated by Django 2.2 on 2019-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_venue_standing_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='standing_capacity',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
